In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import lightgbm as lgb
from lightgbm import LGBMClassifier

In [7]:
df_c= pd.read_csv('../datos/data_Demo.csv', sep=",", index_col=0)

In [8]:
df_c.head()

,Course,Daytime/evening attendance,Mother's occupation,Tuition fees up to date,Scholarship holder,Age at enrollment,credits_enrolled_anual,evaluations_anual,credits_approved_anual,mean_grade_anual,Clasificador(Target)
0,2,1,6,1,0,20,0,0,0,0.000000,1
1,11,1,4,0,0,19,12,12,12,13.833333,0
2,5,1,10,0,0,19,12,0,0,0.000000,1
3,15,1,6,1,0,20,12,18,11,12.914286,0
4,3,0,10,1,0,45,12,15,11,12.666667,0

In [9]:
X= df_c.drop('Clasificador(Target)', axis=1) 
y = df_c['Clasificador(Target)']       

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Hiperparámetros del clasificador LightGBM
lgb_clf = lgb.LGBMClassifier(
    boosting_type='gbdt',   # Método de boosting, 'gbdt' es para Gradient Boosting Decision Tree
    objective='binary',     # Función objetivo para clasificación binaria
    class_weight='balanced',# Peso de las clases para manejar el desbalance
    num_leaves=31,          # Número máximo de hojas en un árbol
    learning_rate=0.05,     # Tasa de aprendizaje
    n_estimators=100,       # Número de árboles de boosting para entrenar
    feature_fraction=0.9,   # Fracción de características a considerar en cada iteración
    bagging_fraction=0.8,   # Fracción de datos de entrenamiento a utilizar en cada iteración
    bagging_freq=5,         # Frecuencia para realizar el bagging
    verbose=-1              # Nivel de verbosidad
)

lgb_clf.fit(X_train, y_train)
y_pred_lgb_clf = lgb_clf.predict(X_test)

# Informe de clasificación
print(classification_report(y_test, y_pred_lgb_clf))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89       569
           1       0.81      0.79      0.80       316

    accuracy                           0.86       885
   macro avg       0.85      0.84      0.84       885
weighted avg       0.86      0.86      0.86       885

In [11]:
import cloudpickle

model =lgb_clf

# Guardar el modelo en un archivo
with open('model.pkl', 'wb') as f:
    cloudpickle.dump(model, f)